name: Docker Build

on:
  push:
    paths:
      - 'docker/**'
  pull_request:
    paths:
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/
          file: docker/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
